#!/usr/bin/env python3
"""Compile reviewed data/scripts into the installer. No runtime script lookup."""
import json
from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parent
policy = json.loads((root / 'applications.json').read_text())
apps = policy['applications']
managers = ('apk', 'apt', 'dnf', 'pacman')
common = (root / 'presets/common.sh').read_text()
quote = lambda s: json.dumps(s, ensure_ascii=True)
lines = ['/* Generated by embed-apps.py; edit applications.json and preset shell files. */']
scripts = {}
seen = set()
for app in apps:
    assert re.fullmatch(r'[a-z][a-z0-9-]*', app['id']) and app['id'] not in seen
    seen.add(app['id'])
    for group in ('packages', 'dependencies', 'scripts'):
        assert set(app.get(group, {})) <= {'all', *managers}
    for script in app.get('scripts', {}).values():
        assert re.fullmatch(r'[a-z][a-z0-9-]*\.sh', script)
        if script not in scripts:
            symbol = 'preset_' + script.replace('-', '_').replace('.', '_')
            text = common + '\n' + (root / 'presets' / script).read_text()
            assert len(text.encode()) <= 4096, (script, 'bounded pipe input exceeded')
            scripts[script] = symbol
            lines.append(f'static const char {symbol}[] = {quote(text)};')
lines.append('static const struct np_application applications[] = {')
for app in apps:
    fields = [quote(app['id']), quote(app['name'])]
    for group in ('packages', 'dependencies', 'scripts'):
        values = []
        table = app.get(group, {})
        for manager in managers:
            value = table.get(manager, table.get('all'))
            if group == 'dependencies' and app.get('scripts', {}).get(manager, app.get('scripts', {}).get('all')):
                value = ' '.join(filter(None, [policy['presetDependencies'][manager], value]))
            if value and group != 'scripts':
                assert all(re.fullmatch(r'[a-zA-Z0-9][a-zA-Z0-9+._:-]*', token) for token in value.split())
            values.append('NULL' if value is None else scripts[value] if group == 'scripts' else quote(value))
        fields.append('{' + ', '.join(values) + '}')
    lines.append('    {' + ', '.join(fields) + '},')
lines.append('};')
output = Path(sys.argv[1])
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text('\n'.join(lines) + '\n')
